IF DB_ID(N'BIBLIOTECA') IS NULL
BEGIN
    CREATE DATABASE BIBLIOTECA;
END;
GO

USE BIBLIOTECA;
GO

IF OBJECT_ID(N'dbo.SOCIO', N'U') IS NULL
    CREATE TABLE dbo.SOCIO
    (
        ID_SOCIO INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_SOCIO_IDSOCIO PRIMARY KEY,
        NOMBRE VARCHAR(50) NOT NULL,
        TELEFONO VARCHAR(50) NOT NULL CONSTRAINT UQ_SOCIO_TELEFONO UNIQUE,
        CORREO VARCHAR(50) NOT NULL CONSTRAINT UQ_SOCIO_CORREO UNIQUE
    );

IF OBJECT_ID(N'dbo.AUTOR', N'U') IS NULL
    CREATE TABLE dbo.AUTOR
    (
        ID_AUTOR INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_AUTOR_ID_AUTOR PRIMARY KEY,
        AUTOR VARCHAR(150) NOT NULL CONSTRAINT UQ_AUTOR_AUTOR UNIQUE
    );

IF OBJECT_ID(N'dbo.EDITORIAL', N'U') IS NULL
    CREATE TABLE dbo.EDITORIAL
    (
        ID_EDITORIAL INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_EDITORIAL_ID_EDITORIAL PRIMARY KEY,
        EDITORIAL VARCHAR(150) NOT NULL CONSTRAINT UQ_EDITORIAL_EDITORIAL UNIQUE
    );

IF OBJECT_ID(N'dbo.LIBRO', N'U') IS NULL
    CREATE TABLE dbo.LIBRO
    (
        ID_LIBRO INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_LIBRO_ID_LIBRO PRIMARY KEY,
        TITULO VARCHAR(200) NOT NULL,
        ID_AUTOR INT NOT NULL CONSTRAINT FK_LIBRO_AUTOR FOREIGN KEY REFERENCES dbo.AUTOR(ID_AUTOR),
        ID_EDITORIAL INT NOT NULL CONSTRAINT FK_LIBRO_EDITORIAL FOREIGN KEY REFERENCES dbo.EDITORIAL(ID_EDITORIAL)
    );

IF OBJECT_ID(N'dbo.PRESTAMO', N'U') IS NULL
    CREATE TABLE dbo.PRESTAMO
    (
        ID_PRESTAMO INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PRESTAMO_ID_PRESTAMO PRIMARY KEY,
        FECHA_PRESTAMO DATETIME2 NOT NULL,
        FECHA_DEVOLUCION DATETIME2 NOT NULL,
        ID_SOCIO INT NOT NULL CONSTRAINT FK_PRESTAMO_SOCIO FOREIGN KEY REFERENCES dbo.SOCIO(ID_SOCIO)
    );

IF OBJECT_ID(N'dbo.DETALLE_PRESTAMO', N'U') IS NULL
    CREATE TABLE dbo.DETALLE_PRESTAMO
    (
        ID_DETALLE_PRESTAMO INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DETALLE_PRESTAMO_ID_DETALLE_PRESTAMO PRIMARY KEY,
        ID_PRESTAMO INT NOT NULL CONSTRAINT FK_DETALLE_PRESTAMO_PRESTAMO FOREIGN KEY REFERENCES dbo.PRESTAMO(ID_PRESTAMO),
        ID_LIBRO INT NOT NULL CONSTRAINT FK_DETALLE_PRESTAMO_LIBRO FOREIGN KEY REFERENCES dbo.LIBRO(ID_LIBRO)
    );
GO

IF NOT EXISTS (SELECT 1 FROM dbo.SOCIO)
    INSERT INTO dbo.SOCIO (NOMBRE, TELEFONO, CORREO) VALUES
        ('JUAN PEREZ', '5551234', 'jperez@gmail.com'),
        ('MARIA LOPEZ', '5555678', 'mlopez@gmail.com'),
        ('CARLOS MARTINEZ', '5559876', 'cmartinez@gmail.com');

IF NOT EXISTS (SELECT 1 FROM dbo.AUTOR)
    INSERT INTO dbo.AUTOR (AUTOR) VALUES
        ('ANTOINE DE SAINT-EXUPERY'), ('GABRIEL GARCIA MARQUEZ'), ('MIGUEL DE CERVANTES');

IF NOT EXISTS (SELECT 1 FROM dbo.EDITORIAL)
    INSERT INTO dbo.EDITORIAL (EDITORIAL) VALUES
        ('SALAMANDRA'), ('SUDAMERICANA'), ('REAL ACADEMIA ESPAÑOLA');

IF NOT EXISTS (SELECT 1 FROM dbo.LIBRO)
    INSERT INTO dbo.LIBRO (TITULO, ID_AUTOR, ID_EDITORIAL) VALUES
        ('EL PRINCIPITO', 1, 1), ('CIEN AÑOS DE SOLEDAD', 2, 2), ('DON QUIJOTE DE LA MANCHA', 3, 3);

IF NOT EXISTS (SELECT 1 FROM dbo.PRESTAMO)
    INSERT INTO dbo.PRESTAMO (FECHA_PRESTAMO, FECHA_DEVOLUCION, ID_SOCIO) VALUES
        ('2026-03-01', '2026-03-15', 1), ('2026-03-02', '2026-03-16', 2), ('2026-03-03', '2026-03-17', 3);

IF NOT EXISTS (SELECT 1 FROM dbo.DETALLE_PRESTAMO)
    INSERT INTO dbo.DETALLE_PRESTAMO (ID_PRESTAMO, ID_LIBRO) VALUES (1, 1), (2, 2), (3, 3);
GO
