CREATE DATABASE BIBLIOTECA;
GO
USE BIBLIOTECA;
CREATE TABLE SOCIO
(
ID_SOCIO INT IDENTITY(1,1) NOT NULL 
	CONSTRAINT PK_SOCIO_IDSOCIO PRIMARY KEY,
NOMBRE VARCHAR(50)NOT NULL,
TELEFONO VARCHAR(50)NOT NULL
	CONSTRAINT UQ_SOCIO_TELEFONO UNIQUE,
CORREO VARCHAR(50) NOT NULL
	CONSTRAINT UQ_SOCIO_CORREO UNIQUE
)


 CREATE TABLE AUTOR
(
	ID_AUTOR INT IDENTITY(1,1) NOT NULL
		CONSTRAINT PK_AUTOR_ID_AUTOR PRIMARY KEY,

	AUTOR VARCHAR(150) NOT NULL
		CONSTRAINT UQ_AUTOR_AUTOR UNIQUE
);


CREATE TABLE EDITORIAL
(
	ID_EDITORIAL INT IDENTITY(1,1) NOT NULL
		CONSTRAINT PK_EDITORIAL_ID_EDITORIAL PRIMARY KEY,

	EDITORIAL VARCHAR(150) NOT NULL
		CONSTRAINT UQ_EDITORIAL_EDITORIAL UNIQUE
);


CREATE TABLE LIBRO
(
	ID_LIBRO INT IDENTITY(1,1) NOT NULL
		CONSTRAINT PK_LIBRO_ID_LIBRO PRIMARY KEY,

	TITULO VARCHAR(200) NOT NULL,

	ID_AUTOR INT NOT NULL
		CONSTRAINT FK_LIBRO_AUTOR
		FOREIGN KEY REFERENCES AUTOR(ID_AUTOR),

	ID_EDITORIAL INT NOT NULL
		CONSTRAINT FK_LIBRO_EDITORIAL
		FOREIGN KEY REFERENCES EDITORIAL(ID_EDITORIAL)
);


CREATE TABLE PRESTAMO 
(
ID_PRESTAMO INT IDENTITY(1,1) NOT NULL
	CONSTRAINT PK_PRESTAMO_ID_PRESTAMO PRIMARY KEY,
FECHA_PRESTAMO DATETIME NOT NULL,
	
FECHA_DEVOLUCION DATETIME NOT NULL,
ID_SOCIO INT NOT NULL
	CONSTRAINT FK_PRESTAMO_SOCIO 
	FOREIGN KEY REFERENCES SOCIO(ID_SOCIO)
)

CREATE TABLE DETALLE_PRESTAMO
(
	ID_DETALLE_PRESTAMO INT IDENTITY(1,1) NOT NULL
		CONSTRAINT PK_DETALLE_PRESTAMO_ID_DETALLE_PRESTAMO PRIMARY KEY,

	ID_PRESTAMO INT NOT NULL
		CONSTRAINT FK_DETALLE_PRESTAMO_PRESTAMO
		FOREIGN KEY REFERENCES PRESTAMO(ID_PRESTAMO),

	ID_LIBRO INT NOT NULL
		CONSTRAINT FK_DETALLE_PRESTAMO_LIBRO
		FOREIGN KEY REFERENCES LIBRO(ID_LIBRO)
);


INSERT INTO SOCIO (NOMBRE, TELEFONO, CORREO)
VALUES
('JUAN PEREZ', '5551234', 'jperez@gmail.com'),
('MARIA LOPEZ', '5555678', 'mlopez@gmail.com'),
('CARLOS MARTINEZ', '5559876', 'cmartinez@gmail.com');

INSERT INTO AUTOR (AUTOR)
VALUES
('ANTOINE DE SAINT-EXUPERY'),
('GABRIEL GARCIA MARQUEZ'),
('MIGUEL DE CERVANTES');

INSERT INTO EDITORIAL (EDITORIAL)
VALUES
('SALAMANDRA'),
('SUDAMERICANA'),
('REAL ACADEMIA ESPAÑOLA');

INSERT INTO LIBRO (TITULO, ID_AUTOR, ID_EDITORIAL)
VALUES
('EL PRINCIPITO', 1, 1),
('CIEN AÑOS DE SOLEDAD', 2, 2),
('DON QUIJOTE DE LA MANCHA', 3, 3);

INSERT INTO PRESTAMO (FECHA_DEVOLUCION, ID_SOCIO)
VALUES
('2026-03-15', 1),
('2026-03-16', 2),
('2026-03-17', 3);

INSERT INTO DETALLE_PRESTAMO (ID_PRESTAMO, ID_LIBRO)
VALUES
(1, 1),
(2, 2),
(3, 3);